### ISSUE TITLE
Não permitir cadastro de reserva com chamado em andamento

### ISSUE THREAD

**Issue by DanielLeiros** [andrefilho99/sigaachave_java#18]

**Comment by jerffesongd** [comment]
@DanielLeiros  e @andrefilho99  seria "remoção de salas com chamados em andamento??"

**Comment by Bhyan** [comment]
@jerffesongd A regra de negocio correta e adicionar reserva em sala com chamado em aberto. Porem não sei se seria legal não poder remover uma sala com um chamado.

**Comment by Bhyan** [comment]
Pelo código que eu fiz se existir chamado para a sala X com status pendente não se deixa cadastrar reserva. Acredito que o ideal seria filtrar por outros status também. Me de um feed back de qual seriam que eu implemento.

**Comment by andrefilho99** [comment]
Quando corrigi a issue 15 essa foi por tabela, pro que temos atualmente acho que esse tratamento serve.
