### ISSUE TITLE
Criar entidade sala

### ISSUE THREAD

**Issue by andrefilho99** [andrefilho99/sigaachave_java#2]
- Se basear em classes já criadas no sistema;
- Obs: Criar repositório, e Enum para tipos de sala;

**Comment by DanielLeiros** [comment]
De acordo com o documento de entrevista não será fixado tipo da sala, pois seu nome erá representar esse aspecto. Então, de acordo com o documento, os campos serão:
- id;
- Nome (nome);
- Localização (localizacao);
- Descrição (descricao);
- Passível de agendamento fixo (permiteFixo).
